# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1F5oeBikXTBhrPbziSEgrH4ySUY2C3b6q
"""

x=5
print(f"变数x的值是：{x}")
print(f"变数x的记忆体地址是：{id(x)}")